runtime: go
api_version: go1

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

handlers:
- url: /css
  static_dir: css
  secure: optional

- url: /images
  static_dir: images
  secure: optional

# All other URLs are handled by the Go application.
- url: /.*
  script: _go_app
  secure: always
